name = "smart-escrow/escrow-dapp"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'smart-escrow/escrow-dapp'"

[repository]
user = "smart-escrow"
project = "escrow-dapp"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
